version: '2'

services:
  tomcat:
    image: 'tomcat'
    build:
      context: .
    container_name: tomcat
    depends_on:
      - postgresDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDb:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080
          
  postgresDb:
    image: 'postgres:13.1-alpine'
    container_name: postgresDb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432